"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
type Vehicle={id:number;number:string;routeNumber:string|null;makeModel:string;year:number|null;openIssues:number}; type SortKey="number"|"route";
const routes=["R-03","R-07","R-11","R-14","R-18","R-22","R-25","R-31"];
function Sidebar(){return <aside className="sidebar"><div className="brand"><span className="brand-mark">K</span><span>KVC <small>ENTERPRISES</small></span></div><nav aria-label="Main navigation"><a href="#"><span>⌂</span> Overview</a><a className="active" href="/"><span>▣</span> Vehicles</a><a href="#"><span>↗</span> Routes</a><a href="#"><span>◷</span> Schedule</a><a href="#"><span>◎</span> Team</a></nav><div className="sidebar-foot"><div className="avatar">KV</div><div><strong>KVC Operations</strong><small>Fleet administrator</small></div></div></aside>}
export function FleetApp(){
 const[vehicles,setVehicles]=useState<Vehicle[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[sort,setSort]=useState<SortKey>("number"),[modal,setModal]=useState<"vehicle"|"issue"|null>(null),[error,setError]=useState("");
 async function load(){setLoading(true);const res=await fetch("/api/vehicles"),data=await res.json();if(res.ok)setVehicles(data.vehicles);else setError(data.error||"Could not load fleet");setLoading(false)} useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>vehicles.filter(v=>`${v.number} ${v.routeNumber||"unassigned"} ${v.makeModel}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="number"?a.number.localeCompare(b.number,undefined,{numeric:true}):(a.routeNumber||"ZZZ").localeCompare(b.routeNumber||"ZZZ",undefined,{numeric:true})),[vehicles,search,sort]);
 const openIssues=vehicles.reduce((s,v)=>s+v.openIssues,0),assigned=vehicles.filter(v=>v.routeNumber).length;
 async function assignRoute(id:number,routeNumber:string){const old=vehicles;setVehicles(v=>v.map(x=>x.id===id?{...x,routeNumber:routeNumber||null}:x));const res=await fetch(`/api/vehicles/${id}/route`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({routeNumber:routeNumber||null})});if(!res.ok){setVehicles(old);setError("Route assignment was not saved.")}}
 return <main className="app-shell"><Sidebar/><section className="workspace"><header className="topbar"><div><p className="eyebrow">FLEET OPERATIONS</p><h1>Vehicles</h1><p className="page-intro">Assignments, maintenance, and fleet readiness in one place.</p></div><div className="header-actions"><button className="secondary" onClick={()=>setModal("vehicle")}>＋ Add vehicle</button><button className="primary" onClick={()=>setModal("issue")}>＋ Report issue</button></div></header>{error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}
 <section className="stats" aria-label="Fleet summary"><article><span className="stat-icon green">▣</span><div><small>TOTAL VEHICLES</small><strong>{vehicles.length}</strong><p><b>{assigned}</b> assigned to routes</p></div></article><article><span className="stat-icon amber">!</span><div><small>OPEN ISSUES</small><strong>{openIssues}</strong><p>Items needing attention</p></div></article><article><span className="stat-icon blue">↗</span><div><small>ROUTES COVERED</small><strong>{new Set(vehicles.map(v=>v.routeNumber).filter(Boolean)).size}</strong><p>Across today’s operation</p></div></article></section>
 <section className="fleet-card"><div className="fleet-head"><div><h2>Fleet roster</h2><p>Assign routes and keep every truck moving.</p></div><div className="fleet-tools"><label className="search">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} aria-label="Search vehicles" placeholder="Search vehicle or route"/></label><div className="sort-toggle"><button className={sort==="number"?"selected":""} onClick={()=>setSort("number")}>Truck #</button><button className={sort==="route"?"selected":""} onClick={()=>setSort("route")}>Route #</button></div></div></div><div className="table-wrap"><table><thead><tr><th>VEHICLE</th><th>ROUTE ASSIGNMENT</th><th>MAKE &amp; MODEL</th><th>OPEN ISSUES</th><th>STATUS</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="empty">Loading fleet…</td></tr>:visible.length===0?<tr><td colSpan={6} className="empty">No vehicles match your search.</td></tr>:visible.map(v=><tr key={v.id}><td><a className="truck-link" href={`/vehicles/${v.id}`}>#{v.number}</a></td><td><select aria-label={`Route for vehicle ${v.number}`} value={v.routeNumber||""} onChange={e=>assignRoute(v.id,e.target.value)}><option value="">Unassigned</option>{routes.map(r=><option key={r}>{r}</option>)}</select></td><td>{v.year?`${v.year} `:""}{v.makeModel}</td><td><span className={v.openIssues?"issue-count alert":"issue-count"}>{v.openIssues}</span></td><td><span className={v.openIssues?"status attention":"status ready"}>● {v.openIssues?"Attention":"Ready"}</span></td><td><a className="row-arrow" href={`/vehicles/${v.id}`} aria-label={`Open vehicle ${v.number}`}>→</a></td></tr>)}</tbody></table></div><footer className="table-foot"><span>{visible.length} vehicle{visible.length===1?"":"s"}</span><span>Route changes save automatically</span></footer></section></section>{modal==="vehicle"&&<VehicleModal onClose={()=>setModal(null)} onSaved={()=>{setModal(null);void load()}}/>}{modal==="issue"&&<IssueModal vehicles={vehicles} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);void load()}}/>}</main>}
function ModalFrame({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">KVC FLEET</p><h2 id="modal-title">{title}</h2><p>{subtitle}</p>{children}</section></div>}
function VehicleModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const[saving,setSaving]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget),res=await fetch("/api/vehicles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});setSaving(false);if(res.ok)onSaved()}return <ModalFrame title="Add a vehicle" subtitle="Add a truck to the KVC fleet roster." onClose={onClose}><form onSubmit={submit} className="form-grid"><label>Vehicle number<input name="number" required placeholder="e.g. 1228" autoFocus/></label><label>Route assignment<select name="routeNumber" defaultValue=""><option value="">Unassigned</option>{routes.map(r=><option key={r}>{r}</option>)}</select></label><label className="wide">Make &amp; model<input name="makeModel" required placeholder="e.g. Ford Transit"/></label><label>Year<input name="year" type="number" min="1990" max="2100" placeholder="2023"/></label><div className="form-actions wide"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?"Adding…":"Add vehicle"}</button></div></form></ModalFrame>}
function IssueModal({vehicles,onClose,onSaved}:{vehicles:Vehicle[];onClose:()=>void;onSaved:()=>void}){const[type,setType]=useState("Maintenance"),[saving,setSaving]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget),res=await fetch("/api/issues",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});setSaving(false);if(res.ok)onSaved()}return <ModalFrame title="Report an issue" subtitle="Log a note or maintenance item for a vehicle." onClose={onClose}><form onSubmit={submit} className="form-grid"><label className="wide">Vehicle<select name="vehicleId" required defaultValue=""><option value="" disabled>Select a vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>#{v.number}{v.routeNumber?` · ${v.routeNumber}`:""}</option>)}</select></label><label className="wide">Issue type<select name="type" value={type} onChange={e=>setType(e.target.value)}><option>Note</option><option>Maintenance</option><option>Other</option></select></label>{type==="Other"&&<label className="wide">What is it?<input name="customType" required placeholder="Describe the issue type"/></label>}<label className="wide">Problem or notes<textarea name="notes" required rows={5} placeholder="What happened? Include any details the team should know."/></label><div className="form-actions wide"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?"Submitting…":"Submit issue"}</button></div></form></ModalFrame>}
