import { createMgbaDswSnapshot, type MgbaDswRouteInput, type MgbaDswSnapshotInput, type MgbaDswStatusPackageInput, type MgbaStatusPackageCaptureState } from "../../../../../services/integrations/mgba-dsw";
import { validInternalBearer } from "../../bearer";

class PayloadError extends Error {}
const MAX_BYTES = 8_000_000;
function object(value: unknown, field: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new PayloadError(`${field} must be an object.`); return value as Record<string, unknown>; }
function text(value: unknown, field: string, required = false, maxLength = 300) { if (value === null || value === undefined || value === "") { if (required) throw new PayloadError(`${field} is required.`); return null; } if (typeof value !== "string" || value.trim().length > maxLength) throw new PayloadError(`${field} must be text no longer than ${maxLength} characters.`); return value.trim() || null; }
function number(value: unknown, field: string, integer = true) { if (value === null || value === undefined || value === "") return null; if (typeof value !== "number" || !Number.isFinite(value) || (integer && !Number.isInteger(value))) throw new PayloadError(`${field} must be a ${integer ? "whole number" : "number"} or null.`); return value; }
function date(value: unknown, field: string) { const parsed = text(value, field, true, 20); if (!/^\d{4}-\d{2}-\d{2}$/.test(parsed || "")) throw new PayloadError(`${field} must use YYYY-MM-DD.`); return parsed as string; }
function bool(value: unknown, field: string) { if (value === undefined) return false; if (typeof value !== "boolean") throw new PayloadError(`${field} must be true or false.`); return value; }
function statusPackage(value: unknown, routeIndex: number, packageIndex: number): MgbaDswStatusPackageInput { const source = object(value, `routes[${routeIndex}].statusPackages[${packageIndex}]`); const prefix = `routes[${routeIndex}].statusPackages[${packageIndex}]`; const packageNumber = number(source.packageNumber, `${prefix}.packageNumber`); if (packageNumber === null || packageNumber < 0) throw new PayloadError(`${prefix}.packageNumber must be a non-negative whole number.`); return { packageNumber, additionalInfo: text(source.additionalInfo, `${prefix}.additionalInfo`, false, 1000), visionLabel: text(source.visionLabel, `${prefix}.visionLabel`, false, 1000), trackingId: text(source.trackingId, `${prefix}.trackingId`, false, 1000), destinationAddress: text(source.destinationAddress, `${prefix}.destinationAddress`, false, 2000), vehicleNumber: text(source.vehicleNumber, `${prefix}.vehicleNumber`, false, 300), vsaStatusCode: text(source.vsaStatusCode, `${prefix}.vsaStatusCode`, false, 300), starStatusCode: text(source.starStatusCode, `${prefix}.starStatusCode`, false, 300), starScanTime: text(source.starScanTime, `${prefix}.starScanTime`, false, 300), isGreyedOut: bool(source.isGreyedOut, `${prefix}.isGreyedOut`) }; }
function row(value: unknown, index: number): MgbaDswRouteInput {
  const source = object(value, `routes[${index}]`); const prefix = `routes[${index}]`;
  const driverName = text(source.driverName, `${prefix}.driverName`, false);
  const routeNumber = text(source.route, `${prefix}.route`, false, 80); const rawRoute = text(source.rawRoute, `${prefix}.rawRoute`, false, 80); if (!routeNumber && !rawRoute) throw new PayloadError(`${prefix} must include a route or rawRoute.`);
  const sourcePackages = source.statusPackages; if (sourcePackages !== undefined && !Array.isArray(sourcePackages)) throw new PayloadError(`${prefix}.statusPackages must be an array.`); const statusPackages = (sourcePackages || []).map((item, packageIndex) => statusPackage(item, index, packageIndex));
  const requestedState = source.statusPackageCaptureState ?? source.statusPackagesState; const allowedStates: readonly MgbaStatusPackageCaptureState[] = ["not_applicable", "captured", "incomplete", "failed"]; if (requestedState !== undefined && (typeof requestedState !== "string" || !allowedStates.includes(requestedState as MgbaStatusPackageCaptureState))) throw new PayloadError(`${prefix}.statusPackageCaptureState is invalid.`);
  const count = number(source.allStatusCodePkgs, `${prefix}.allStatusCodePkgs`); let statusPackagesState: MgbaStatusPackageCaptureState = (requestedState as MgbaStatusPackageCaptureState | undefined) || (count && count > 0 ? (sourcePackages === undefined ? "failed" : statusPackages.length === count ? "captured" : "incomplete") : "not_applicable");
  if ((!count || count <= 0) && statusPackages.length) throw new PayloadError(`${prefix}.statusPackages requires a positive allStatusCodePkgs count.`); if (statusPackagesState === "not_applicable" && statusPackages.length) throw new PayloadError(`${prefix}.statusPackages cannot be supplied when capture is not applicable.`); if (statusPackagesState === "captured" && count !== statusPackages.length) statusPackagesState = "incomplete";
  return { serviceArea: text(source.serviceArea, `${prefix}.serviceArea`), waName: text(source.waName, `${prefix}.waName`), vehicleNumber: text(source.vehicleNumber, `${prefix}.vehicleNumber`), driverName: driverName || "",
    routeNumber, rawRoute, dst: text(source.dst, `${prefix}.dst`),
    vscanPkgs: number(source.vscanPkgs, `${prefix}.vscanPkgs`), delStops: number(source.delStops, `${prefix}.delStops`), puStops: number(source.puStops, `${prefix}.puStops`), diff: number(source.diff, `${prefix}.diff`),
    actDelStops: number(source.actDelStops, `${prefix}.actDelStops`), actDelPkgs: number(source.actDelPkgs, `${prefix}.actDelPkgs`), actPuStops: number(source.actPuStops, `${prefix}.actPuStops`), actPuPkgs: number(source.actPuPkgs, `${prefix}.actPuPkgs`),
    ilsPercent: number(source.ilsPercent, `${prefix}.ilsPercent`, false), nextAvailOnDuty: text(source.nextAvailOnDuty, `${prefix}.nextAvailOnDuty`), allStatusCodePkgs: count, driverOrder: number(source.driverOrder, `${prefix}.driverOrder`) ?? 0, statusPackagesState, statusPackages };
}
export function parseMgbaDswPayload(value: unknown): MgbaDswSnapshotInput {
  const source = object(value, "Request body"); const operationalDate = date(source.operationalDate, "operationalDate"); const dswDate = text(source.dswDate, "dswDate", true, 20) as string;
  const capturedAt = text(source.capturedAt, "capturedAt", true, 100) as string; if (Number.isNaN(Date.parse(capturedAt))) throw new PayloadError("capturedAt must be an ISO timestamp.");
  const rows = source.routes; if (!Array.isArray(rows) || rows.length > 2000) throw new PayloadError("routes must be an array with no more than 2000 driver rows.");
  const normalizedRows = rows.map(row);
  return { operationalDate, dswDate, capturedAt, source: (text(source.source, "source", true, 80) as string), routeCount: normalizedRows.length, routes: normalizedRows };
}
export async function POST(request: Request) {
  if (!validInternalBearer(request, process.env.MGBA_INGEST_TOKEN)) return Response.json({ error: "Valid ingestion credentials are required.", code: "MGBA_INGEST_UNAUTHORIZED" }, { status: 401 });
  const length = Number(request.headers.get("content-length") || 0); if (Number.isFinite(length) && length > MAX_BYTES) return Response.json({ error: "Request body is too large.", code: "MGBA_INGEST_TOO_LARGE" }, { status: 413 });
  try { const snapshot = await createMgbaDswSnapshot(parseMgbaDswPayload(await request.json())); return Response.json({ snapshotId: snapshot.id, operationalDate: snapshot.operationalDate, capturedAt: snapshot.capturedAt, created: snapshot.created, deduplicated: snapshot.deduplicated }, { status: 201 }); }
  catch (error) { if (error instanceof PayloadError || error instanceof SyntaxError) return Response.json({ error: error instanceof PayloadError ? error.message : "Request body must be valid JSON.", code: "MGBA_INGEST_INVALID" }, { status: 400 }); const errorId = crypto.randomUUID(); console.error("MGBA DSW ingestion failed", { errorId }); return Response.json({ error: "The Monitor snapshot could not be saved.", code: "MGBA_INGEST_FAILED", errorId }, { status: 500 }); }
}
